---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-ci
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: drone-ci
  namespace: default
  annotations:
    kubernetes.io/service-account.name: drone-ci
type: kubernetes.io/service-account-token
